name: Build DeadCode

on:
  workflow_dispatch: # Ручной запуск через интерфейс GitHub
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: Stealer-DeadCode
        fetch-depth: 0

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
        static: true
        version: '13.2.0'

    - name: Verify MinGW installation
      run: |
        $mingwBinPath = "C:/mingw64/bin"
        if (-not (Test-Path $mingwBinPath)) {
          Write-Host "Ошибка: Каталог MinGW bin не найден по пути $mingwBinPath"
          exit 1
        }
        $env:Path = "$mingwBinPath;" + $env:Path
        if (-not (Get-Command "g++" -ErrorAction SilentlyContinue)) {
          Write-Host "Ошибка: g++ не найден в PATH"
          exit 1
        }
        Write-Host "Версия g++:"
        & g++ --version
        if (-not (Get-Command "make" -ErrorAction SilentlyContinue)) {
          Write-Host "Ошибка: make не найден в PATH"
          exit 1
        }
        Write-Host "Версия make:"
        & make --version
      shell: powershell

    - name: Install CMake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: '3.28.0'
      continue-on-error: false

    - name: Verify CMake installation
      run: |
        $cmakePath = "cmake"
        if (-not (Get-Command $cmakePath -ErrorAction SilentlyContinue)) {
          Write-Host "Ошибка: cmake не найден в PATH"
          exit 1
        }
        Write-Host "Версия CMake:"
        & $cmakePath --version
      shell: powershell

    - name: Install Ninja
      run: |
        Write-Host "Установка Ninja..."
        choco install ninja -y
        $ninjaPath = "ninja"
        if (-not (Get-Command $ninjaPath -ErrorAction SilentlyContinue)) {
          Write-Host "Ошибка: ninja не найден в PATH"
          exit 1
        }
        Write-Host "Версия Ninja:"
        & $ninjaPath --version
      shell: powershell

    - name: Install Perl
      run: |
        Write-Host "Установка Perl..."
        choco install strawberryperl -y
        $perlPath = "perl"
        if (-not (Get-Command $perlPath -ErrorAction SilentlyContinue)) {
          Write-Host "Ошибка: perl не найден в PATH"
          exit 1
        }
        Write-Host "Версия Perl:"
        & $perlPath --version
      shell: powershell

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw81'
        dir: 'C:/Qt'
        cache: true

    - name: Cache vcpkg
      uses: actions/cache@v4
      with:
        path: C:/vcpkg
        key: vcpkg-${{ hashFiles('**/vcpkg.json') }}
        restore-keys: |
          vcpkg-

    - name: Install vcpkg and dependencies
      run: |
        if (-not (Test-Path C:/vcpkg)) {
          Write-Host "Клонирование vcpkg..."
          git clone https://github.com/microsoft/vcpkg.git C:/vcpkg
          Write-Host "Обновление vcpkg до последней версии..."
          cd C:/vcpkg
          git pull origin master
          cd ../
          Write-Host "Запуск bootstrap-vcpkg..."
          & C:/vcpkg/bootstrap-vcpkg.bat -disableMetrics
          if ($LASTEXITCODE -ne 0) {
            Write-Host "Ошибка: Bootstrap завершился с ошибкой. Проверьте логи."
            exit 1
          }
        }
        # Проверка существования vcpkg.exe
        $vcpkgExe = "C:/vcpkg/vcpkg.exe"
        if (-not (Test-Path $vcpkgExe)) {
          Write-Host "Ошибка: vcpkg.exe не найден по пути $vcpkgExe"
          exit 1
        }
        $env:Path = "C:/vcpkg;" + $env:Path
        # Вывод версии vcpkg
        Write-Host "Версия vcpkg:"
        & $vcpkgExe --version
        # Проверка Perl
        Write-Host "Проверка Perl перед установкой..."
        & perl --version
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Ошибка: Perl не работает корректно"
          exit 1
        }
        # Очистка кэша vcpkg
        Write-Host "Очистка кэша vcpkg..."
        & $vcpkgExe remove --outdated --recurse
        # Полная очистка buildtrees
        Write-Host "Очистка vcpkg buildtrees..."
        Remove-Item -Path "C:/vcpkg/buildtrees" -Recurse -Force -ErrorAction SilentlyContinue
        Write-Host "Установка зависимостей vcpkg с триплетом x64-mingw-static..."
        & $vcpkgExe install sqlite3 libzip zlib bzip2 openssl --triplet x64-mingw-static --clean-after-build --debug --debug-env --x-build-concurrency=1 > vcpkg_install.log 2>&1
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Ошибка: vcpkg install завершился с ошибкой. Проверьте логи для деталей."
          Get-Content vcpkg_install.log
          dir C:/vcpkg/installed/x64-mingw-static/lib
          # Вывод логов для отладки
          Write-Host "Вывод логов vcpkg..."
          dir C:/vcpkg/buildtrees/openssl
          if (Test-Path C:/vcpkg/buildtrees/openssl/install-x64-mingw-static-rel-err.log) {
            Write-Host "Содержимое install-x64-mingw-static-rel-err.log:"
            Get-Content C:/vcpkg/buildtrees/openssl/install-x64-mingw-static-rel-err.log
          }
          if (Test-Path C:/vcpkg/buildtrees/openssl/install-x64-mingw-static-rel-out.log) {
            Write-Host "Содержимое install-x64-mingw-static-rel-out.log:"
            Get-Content C:/vcpkg/buildtrees/openssl/install-x64-mingw-static-rel-out.log
          }
          exit 1
        }
        Write-Host "Установка vcpkg завершена успешно"
      shell: powershell

    - name: Upload vcpkg logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: vcpkg-logs
        path: |
          C:/vcpkg/vcpkg_install.log
          C:/vcpkg/buildtrees/openssl/install-x64-mingw-static-rel-err.log
          C:/vcpkg/buildtrees/openssl/install-x64-mingw-static-rel-out.log
        if-no-files-found: warn

    - name: Verify vcpkg installation
      run: |
        $libDir = "C:/vcpkg/installed/x64-mingw-static/lib"
        $includeDir = "C:/vcpkg/installed/x64-mingw-static/include"
        $libs = @("sqlite3", "zip", "z", "bz2", "ssl", "crypto")
        $headers = @("sqlite3.h", "zip.h", "zlib.h", "bzlib.h", "openssl/ssl.h", "openssl/crypto.h")
        $missing = @()
        foreach ($lib in $libs) {
          if (-not (Test-Path "$libDir/lib$lib.a")) {
            $missing += "lib$lib.a"
          }
        }
        foreach ($header in $headers) {
          if (-not (Test-Path "$includeDir/$header")) {
            $missing += $header
          }
        }
        if ($missing) {
          Write-Host "Ошибка: Отсутствуют библиотеки или заголовочные файлы: $missing"
          Write-Host "Содержимое каталога ${libDir}:"
          dir ${libDir}
          Write-Host "Содержимое каталога ${includeDir}:"
          dir ${includeDir}
          exit 1
        }
        Write-Host "Все зависимости vcpkg проверены"
      shell: powershell

    - name: Verify Qt installation
      run: |
        $qmakePath = "C:/Qt/5.15.2/mingw81_64/bin/qmake.exe"
        if (-not (Test-Path $qmakePath)) {
          Write-Host "Ошибка: qmake не найден по пути $qmakePath"
          exit 1
        }
        $env:Path = "C:/Qt/5.15.2/mingw81_64/bin;C:/Qt/Tools/mingw810_64/bin;C:/mingw64/bin;" + $env:Path
        & $qmakePath --version
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Ошибка: qmake --version завершился с ошибкой"
          exit 1
        }
        Write-Host "Установка Qt проверена"
      shell: powershell

    - name: Verify project structure
      run: |
        cd Stealer-DeadCode
        if (-not (Test-Path ui/DeadCode.pro)) {
          Write-Host "Ошибка: DeadCode.pro не найден в ui/"
          dir ui
          exit 1
        }
        if (-not (Test-Path src/main.cpp)) {
          Write-Host "Ошибка: main.cpp не найден в src/"
          dir src
          exit 1
        }
        if (-not (Test-Path ui/mainwindow.ui)) {
          Write-Host "Ошибка: mainwindow.ui не найден в ui/"
          dir ui
          exit 1
        }
        if (-not (Test-Path ui/mainwindow.cpp)) {
          Write-Host "Ошибка: mainwindow.cpp не найден в ui/"
          dir ui
          exit 1
        }
        if (-not (Test-Path ui/mainwindow.h)) {
          Write-Host "Ошибка: mainwindow.h не найден в ui/"
          dir ui
          exit 1
        }
        Write-Host "Структура проекта проверена"
      shell: powershell

    - name: Generate headers
      run: |
        cd Stealer-DeadCode
        if (-not (Test-Path src/build_key.h)) {
          New-Item -Path src -Name build_key.h -ItemType File -Force
          Add-Content src/build_key.h ""
        }
        if (-not (Test-Path src/polymorphic_code.h)) {
          New-Item -Path src -Name polymorphic_code.h -ItemType File -Force
          Add-Content src/polymorphic_code.h ""
        }
        if (-not (Test-Path src/junk_code.h)) {
          New-Item -Path src -Name junk_code.h -ItemType File -Force
          Add-Content src/junk_code.h ""
        }
      shell: powershell

    - name: Configure and build
      run: |
        cd Stealer-DeadCode
        $env:Path = "C:/Qt/5.15.2/mingw81_64/bin;C:/Qt/Tools/mingw810_64/bin;C:/mingw64/bin;C:/vcpkg/installed/x64-mingw-static/bin;" + $env:Path
        $env:INCLUDE = "C:/vcpkg/installed/x64-mingw-static/include;" + $env:INCLUDE
        $env:LIB = "C:/vcpkg/installed/x64-mingw-static/lib;" + $env:LIB
        & qmake -spec win32-g++ ui/DeadCode.pro -o Makefile
        if (-not (Test-Path Makefile)) {
          Write-Host "Ошибка: Makefile не был сгенерирован"
          exit 1
        }
        & mingw32-make -f Makefile.Release
        if (-not (Test-Path ../build/DeadCode.exe)) {
          Write-Host "Ошибка: DeadCode.exe не был создан"
          dir ../build
          exit 1
        }
        if (Test-Path ui/icon.ico) {
          Copy-Item ui/icon.ico ../build/icon.ico
          Write-Host "Иконка скопирована в каталог сборки"
        }
        if (Test-Path src/build_key.h) {
          Copy-Item src/build_key.h ../build/build_key.h
          Write-Host "build_key.h скопирован в каталог сборки"
        }
        if (Test-Path src/polymorphic_code.h) {
          Copy-Item src/polymorphic_code.h ../build/polymorphic_code.h
          Write-Host "polymorphic_code.h скопирован в каталог сборки"
        }
      shell: powershell

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DeadCode.exe
        path: Stealer-DeadCode/../build/DeadCode.exe

    - name: Cleanup
      if: always()
      run: |
        Remove-Item -Path "C:/vcpkg" -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item -Path "C:/Qt" -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item -Path "C:/mingw64" -Recurse -Force -ErrorAction SilentlyContinue
      shell: powershell